var scripts = [
	{
		name: "mission",
		author: "schraf",
		extension: "",
		tags: ["games", "graphics"],
	}, {
		name: "couleur",
		author: "antarctus",
		extension: "",
		tags: ["utility", "graphics"],
	}, {
		name: "tanks",
		author: "antarctus",
		extension: "",
		tags: ["games", "graphics", "multiplayer"],
	}, {
		name: "the_snake",
		author: "antarctus",
		extension: "",
		tags: ["games", "graphics", "snake", "module"],
	}, {
		name: "the_snake_game",
		author: "antarctus",
		extension: "error.png",
		tags: ["games", "graphics", "snake",],
	}, {
		name: "lou",
		author: "antarctus",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "minecraft",
		author: "antarctus",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "doodle_man",
		author: "fime",
		extension: "fime-doodle_man.gif",
		tags: ["games", "graphics",],
	}, {
		name: "pong",
		author: "fime",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "pong2",
		author: "fime",
		extension: "fime-pong2.gif",
		tags: ["games", "graphics", "alternative-only",],
	}, {
		name: "cyclope_snake",
		author: "fime",
		extension: "fime-cyclope_snake.gif",
		tags: ["games", "graphics", "snake",],
	}, {
		name: "pacman",
		author: "fedyna-kevin",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "tetris",
		author: "fedyna-kevin",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "jetpack_bird",
		author: "fime",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "snake",
		author: "arthurjacquin",
		extension: "",
		tags: ["games", "graphics", "snake",],
	}, {
		name: "sokoban_demo",
		author: "cent20",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "treasure",
		author: "cent20",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "conway",
		author: "fedyna-kevin",
		extension: "",
		tags: ["graphics", "experimental"],
	}, {
		name: "demine",
		author: "cent20",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "solar",
		author: "jilsaint90",
		extension: "",
		tags: ["utility", "graphics",],
	}, {
		name: "g2048",
		author: "pokegali",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "snake",
		author: "golem64",
		extension: "",
		tags: ["games", "graphics", "snake",],
	}, {
		name: "platformer",
		author: "golem64",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "chute",
		author: "antarctus",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "pixelart",
		author: "squidinkrf",
		extension: "",
		tags: ["utility", "graphics", "alternative-only",],
	}, {
		name: "morpion",
		author: "florian-allard",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "planeur_bombe",
		author: "florian-allard",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "toutnoirtoutblanc",
		author: "florian-allard",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "nuum",
		author: "numworks",
		extension: "",
		tags: ["games", "graphics", "3D",],
	}, {
		name: "fete_nationale",
		author: "numworks",
		extension: "",
		tags: ["graphics", "animation"],
	}, {
		name: "saint_patrick",
		author: "numworks",
		extension: "",
		tags: ["games", "graphics",],
	}, {
		name: "tron",
		author: "schraf",
		extension: "",
		tags: ["games", "graphics", "multiplayer",],
	}, {
		name: "snake",
		author: "eta45",
		extension: "",
		tags: ["games", "graphics", "snake",],
	}, {
		name: "codebarre",
		author: "nicolas-patrois",
		extension: "",
		tags: ["utility", "graphics"],
	}, {
		name: "snake",
		author: "nicolas-patrois",
		extension: "",
		tags: ["games", "graphics", "snake"],
	}, {
		name: "snake",
		author: "airopi",
		extension: "",
		tags: ["games", "graphics", "snake"],
	}, {
		name: "sobokan",
		author: "escartem",
		extension: "",
		tags: ["games", "graphics"],
	}, {
		name: "infantryfight",
		author: "eta45",
		extension: "error.png",
		tags: ["games", "graphics", "multiplayer", "alternative-only"],
	}, {
		name: "copytxt",
		author: "fime",
		extension: "",
		tags: ["graphics", "module"],
	}, {
		name: "menulib2",
		author: "fime",
		extension: "",
		tags: ["graphics", "module"],
	}, {
		name: "pong",
		author: "florian-allard",
		extension: "",
		tags: ["graphics", "games", "multiplayer"],
	}, {
		name: "battleship",
		author: "alex-juge84",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "hongrois",
		author: "schraf",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "rubika",
		author: "schraf",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "halloween",
		author: "schraf",
		extension: "",
		tags: ["graphics", "animation", "art"],
	}, {
		name: "mohr",
		author: "schraf",
		extension: "",
		tags: ["graphics", "animation", "art"],
	}, {
		name: "anykeys",
		author: "mobluse",
		extension: "",
		tags: ["graphics", "utility"],
	}, {
		name: "bataille_navale",
		author: "ph-moutou",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "mem",
		author: "andreanx",
		extension: "",
		tags: ["utility"],
	}, {
		name: "sofus",
		author: "alain-busser",
		extension: "",
		tags: ["experimental",],
	}, {
		name: "brainfuck",
		author: "nicolas-patrois",
		extension: "",
		tags: ["experimental",],
	}, {
		name: "feu",
		author: "antarctus",
		extension: "",
		tags: ["graphics", "animation", "art"],
	}, {
		name: "phy_atomic",
		author: "antarctus",
		extension: "",
		tags: ["graphics", "utility"],
	}, {
		name: "disco",
		author: "schraf",
		extension: "",
		tags: ["graphics", "animation", "art"],
	}, {
		name: "raytrace",
		author: "andreanx",
		extension: "",
		tags: ["graphics", "art"],
	}, {
		name: "taquin",
		author: "florian-allard",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "an2022",
		author: "schraf",
		extension: "",
		tags: ["graphics", "utility"],
	}, {
		name: "calendrier",
		author: "antarctus",
		extension: "",
		tags: ["graphics", "utility"]
	}, {
		name: "chronometre",
		author: "antarctus",
		extension: "",
		tags: ["graphics", "utility", "animation"],
	}, {
		name: "game_2048",
		author: "cent20",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "ddlc",
		author: "frablock",
		extension: "",
		tags: ["graphics", "games", "alternative-only"],
	}, {
		name: "sautemouton",
		author: "andreanx",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "mastermind",
		author: "schraf",
		extension: "",
		tags: ["games"],
	}, {
		name: "the_space_game",
		author: "opktmgb",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "geometry_dash_v4",
		author: "loic-azavant",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "matrix",
		author: "elodie-gamot",
		extension: "",
		tags: ["graphics", "animation"],
	}, {
		name: "colors",
		author: "ikario198",
		extension: "",
		tags: ["graphics", "utility"],
	}, {
		name: "factors",
		author: "ikario198",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "pipemania",
		author: "schraf",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "gif_dance",
		author: "schraf",
		extension: "",
		tags: ["graphics", "animation"],
	}, {
		name: "labylowmini",
		author: "pardouin",
		extension: "",
		tags: ["graphics", "games", "3D"],
	}, {
		name: "galaxie",
		author: "schraf",
		extension: "",
		tags: ["graphics", "art"],
	}, {
		name: "jeu_allumettes_graph",
		author: "numworks",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "ruin",
		author: "fime",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "karas",
		author: "yaya-cout",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "penguin_life",
		author: "squarepoint",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "ball3d",
		author: "schraf",
		extension: "",
		tags: ["graphics", "art"],
	}, {
		name: "cube222",
		author: "schraf",
		extension: "",
		tags: ["graphics", "games", "3D"],
	}, {
		name: "demo3d",
		author: "squarepoint",
		extension: "",
		tags: ["graphics", "animation", "3D"],
	}, {
		name: "menger",
		author: "schraf",
		extension: "",
		tags: ["graphics", "art", "3D"],
	}, {
		name: "tetris",
		author: "ziii",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "minecraft_terrain_generator",
		author: "naul",
		extension: "",
		tags: ["graphics", "3D"],
	}, {
		name: "philo",
		author: "jilsaint90",
		extension: "",
		tags: ["utility"],
	}, {
		name: "minesweeper",
		author: "arthurjacquin",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "tetris",
		author: "zecake",
		extension: "",
		tags: ["graphics", "games"],
	}, {
		name: "entropia_auto",
		author: "gianfranco-oddenino",
		extension: "",
		tags: ["graphics", "utility"],
	}, {
		name: "puissance4",
		author: "r0baiyn",
		extension: "",
		tags: ["graphics", "games", "multiplayer"],
	}, {
		name: "reversi",
		author: "thomas-s",
		extension: "",
		tags: ["graphics", "games", "multiplayer"],
	}, {
		name: "sudoku",
		author: "anaali",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034,
	}, {
		name: "Towers of Hanoi",
		author: "WhiteOwl",
		upsilonLink: "https://yaya-cout.github.io/Upsilon-Workshop/view/76c8ff40-a94c-4b59-83ea-df5eb6876ba4",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034,
	}, {
		name: "tir_a_la_corde",
		author: "elnix90",
		extension: "",
		tags: ["graphics", "games", "multiplayer"],
		release: 1688040076034 + 0 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "verbes_irreguliers",
		author: "eloidrai1",
		extension: "",
		tags: ["utility"],
		release: 1688040076034 + 1 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "taquin",
		author: "escartem",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 2 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "puissance4",
		author: "florian-allard",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 3 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "microtext",
		author: "tristan-lusson",
		extension: "",
		tags: ["graphics", "module"],
		release: 1688040076034 + 4 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "tetris",
		author: "wperez274",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 5 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "minesweeper",
		author: "maelstudio",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 6 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "chess",
		author: "mdub",
		upsilonLink: "https://yaya-cout.github.io/Upsilon-Workshop/edit/111ec830-5993-41be-bd66-bfc92a80f5a5",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 7 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "mastermind",
		author: "ilyas-r",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 8 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "puissance4",
		author: "gengisclan",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 9 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "game",
		author: "eloidrai1",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 10 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "cliker_simulatorv3",
		author: "pommecrafter",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 11 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "coingame",
		author: "x-keyscore",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 12 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "bombermaths",
		author: "rockingchair1196",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 13 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "flappy_jules",
		author: "elnix91",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 14 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "chess_game",
		author: "aychille",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 15 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "gimpnumworks",
		author: "schraf",
		extension: "",
		tags: ["graphics"],
		release: 1688040076034 + 16 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "render3d1",
		author: "lulu-python",
		extension: "",
		tags: ["graphics", "animation", "3D"],
		release: 1688040076034 + 17 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "growners",
		author: "systeme-eratz",
		extension: "",
		tags: ["graphics", "games"],
		release: 1688040076034 + 18 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "geo_guessr",
		author: "stimorol",
		extension: "",
		tags: ["games"],
		release: 1688040076034 + 19 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "pixelpte",
		author: "squarepoint",
		extension: "",
		tags: ["graphics", "module"],
		release: 1688040076034 + 20 * (60 * 60 * 24 * 7 * 1000),
	}, {
		name: "noel2022",
		author: "andreanx",
		extension: "",
		tags: ["graphics", "animation"],
		release: 1688040076034 + 21 * (60 * 60 * 24 * 7 * 1000),
	}
]
